# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ripple-anaf}
  s.version = "0.8.0.beta1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Kaney"]
  s.date = %q{2010-09-05}
  s.description = %q{Adds the DSL for ANAF for Ripple, an ORM for Riak}
  s.email = %q{brian@vermonster.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ripple-anaf.rb",
     "lib/ripple-anaf/core_ext.rb",
     "lib/ripple-anaf/core_ext/hash.rb",
     "lib/ripple-anaf/document/key.rb",
     "lib/ripple-anaf/nested_attributes.rb",
     "spec/lib/nested_attributes_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/models/car.rb",
     "spec/support/models/driver.rb",
     "spec/support/models/engine.rb",
     "spec/support/models/passenger.rb",
     "spec/support/models/seat.rb",
     "spec/support/models/wheel.rb"
  ]
  s.homepage = %q{http://github.com/bkaney/ripple-anaf}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Accepts-nested-attributes-for support for Ripple}
  s.test_files = [
    "spec/lib/nested_attributes_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/models/car.rb",
     "spec/support/models/driver.rb",
     "spec/support/models/engine.rb",
     "spec/support/models/passenger.rb",
     "spec/support/models/seat.rb",
     "spec/support/models/wheel.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0.beta.19"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<ripple>, ["= 0.8.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.19"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<ripple>, ["= 0.8.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.19"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<ripple>, ["= 0.8.0"])
  end
end

